### ISSUE TITLE
The size of the pre-trained rgb weights

### ISSUE THREAD

**Issue by erizmr** [Linyou/taichi-ngp-renderer#3]
The output size of the rgb layer is 3. However, a size of 64\*8 is allocated for the last layer in `self.rgb_weights` instead of  64\*3.
`self.rgb_weights= ti.field(dtype=data_type, shape=(layer2_base+64*8,))`. 
I am wondering if I missed something or there any specific reasons for this? 
Thanks!

**Comment by Linyou** [comment]
Hi @erizmr 

The reason for using `64*8` instead of `64*3` is for memory alignment and only using the first three elements (RGB). The rest is just padding.

However, I don't know whether this memory layout would affect the Taichi SharedArray when doing computation or data copy.

Also, here is just directly following the original implementation since they force the weight size to be the factor of 8 and 16 for `mlp`. Note that, the `tiny-cuda-nn` will have `64*8` for `cublas` and `64*16` for `fully fused mlp`

The pre-trained weight I provide is trained on `cublas`, so it would have a `64*8` size for the last layer.

**Comment by erizmr** [comment]
Very clear. Thanks for the reply!
